// <auto-generated />
namespace CyberSecurity_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class insertData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(insertData));
        
        string IMigrationMetadata.Id
        {
            get { return "202212131654349_insertData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
